// this proto file contains definitions for communication between the client and the name node

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ghost.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GhostService_Hello_FullMethodName = "/proto.GhostService/Hello"
)

// GhostServiceClient is the client API for GhostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GhostServiceClient interface {
	Hello(ctx context.Context, in *HelloMsg, opts ...grpc.CallOption) (*HelloMsg, error)
}

type ghostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGhostServiceClient(cc grpc.ClientConnInterface) GhostServiceClient {
	return &ghostServiceClient{cc}
}

func (c *ghostServiceClient) Hello(ctx context.Context, in *HelloMsg, opts ...grpc.CallOption) (*HelloMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloMsg)
	err := c.cc.Invoke(ctx, GhostService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GhostServiceServer is the server API for GhostService service.
// All implementations must embed UnimplementedGhostServiceServer
// for forward compatibility.
type GhostServiceServer interface {
	Hello(context.Context, *HelloMsg) (*HelloMsg, error)
	mustEmbedUnimplementedGhostServiceServer()
}

// UnimplementedGhostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGhostServiceServer struct{}

func (UnimplementedGhostServiceServer) Hello(context.Context, *HelloMsg) (*HelloMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedGhostServiceServer) mustEmbedUnimplementedGhostServiceServer() {}
func (UnimplementedGhostServiceServer) testEmbeddedByValue()                      {}

// UnsafeGhostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GhostServiceServer will
// result in compilation errors.
type UnsafeGhostServiceServer interface {
	mustEmbedUnimplementedGhostServiceServer()
}

func RegisterGhostServiceServer(s grpc.ServiceRegistrar, srv GhostServiceServer) {
	// If the following call pancis, it indicates UnimplementedGhostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GhostService_ServiceDesc, srv)
}

func _GhostService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GhostService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).Hello(ctx, req.(*HelloMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// GhostService_ServiceDesc is the grpc.ServiceDesc for GhostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GhostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GhostService",
	HandlerType: (*GhostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GhostService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ghost.proto",
}
