# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ghost.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ghost.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bghost.proto\x12\x05proto\"\x18\n\x08HelloMsg\x12\x0c\n\x04name\x18\x01 \x01(\t29\n\x0cGhostService\x12)\n\x05Hello\x12\x0f.proto.HelloMsg\x1a\x0f.proto.HelloMsgB\x0cZ\n../api;apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ghost_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n../api;api'
  _globals['_HELLOMSG']._serialized_start=22
  _globals['_HELLOMSG']._serialized_end=46
  _globals['_GHOSTSERVICE']._serialized_start=48
  _globals['_GHOSTSERVICE']._serialized_end=105
# @@protoc_insertion_point(module_scope)
